### ISSUE TITLE
"Attr" Argument Deprecated in 1.10.6 (GoogleMarketingPlatformBaseOperator)

### ISSUE THREAD

**Issue by KingsleyKelly** [google/orchestra#18]
[Apache has updated the following function](https://github.com/apache/airflow/blob/master/UPDATING.md#baseoperatorrender_template-function-signature-changed) to not use attr.

The following argument is used in [Google Marketing Operator](https://github.com/google/orchestra/blob/43a0849b8245ce1dc35d7191fae25e30f6732e35/orchestra/google/marketing_platform/operators/marketing_platform.py)

**Comment by ceoloide** [comment]
Fixed in 2.1.1
